name: "Generate Artifact Names"
description: "Generates both the standard JFrog artifact name and the temporary GitHub artifact name"

inputs:
  artifact-file-name:
    description: "The base artifact name for JFrog"
    required: true

outputs:
  jfrog_artifact_name:
    description: "The standard JFrog artifact name for final use"
    value: ${{ steps.generate-names.outputs.jfrog_artifact_name }}
  temp_artifact_name:
    description: "The temporary artifact name for GitHub upload"
    value: ${{ steps.generate-names.outputs.temp_artifact_name }}

runs:
  using: "composite"
  steps:
    - name: Get Branch Name
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_ENV

    - name: Generate Artifact Names
      id: generate-names
      run: |
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
        TEMP_ARTIFACT_NAME="temp-build-artifact-${GITHUB_RUN_NUMBER}"
        JFROG_ARTIFACT_NAME="${{ inputs.artifact-file-name }}-${SHORT_SHA}-${GITHUB_RUN_NUMBER}"

        # Setting outputs for the composite action
        echo "temp_artifact_name=$TEMP_ARTIFACT_NAME" >> $GITHUB_OUTPUT
        echo "jfrog_artifact_name=$JFROG_ARTIFACT_NAME" >> $GITHUB_OUTPUT

        echo "Temporary artifact name: $TEMP_ARTIFACT_NAME"
        echo "JFrog artifact name: $JFROG_ARTIFACT_NAME"
