name: 'Zip Artifact'
description: 'Zip artifacts using the provided version number'
inputs:
  source:
    description: 'The path to the folder or file to zip'
    required: true
  destination:
    description: 'The name of the zip file to be created'
    required: true
  version:
    description: 'The version number to include in the artifact name'
    required: true
outputs:
  zip_path:
    description: 'The path to the zipped artifact'
runs:
  using: 'composite'
  steps:
    - name: Zip the artifact
      shell: bash
      run: |
        zip_name="artifact-${{ inputs.version }}.zip"  # Create the zip file in the current directory
        zip -r $zip_name ${{ inputs.source }}          # Zip the source directory into the current directory
        echo "zip_path=$zip_name" >> $GITHUB_OUTPUT    # Set the output for zip_path

    - name: Debug
      shell: bash
      run: ls -la
