allowed_jfrog_pushes:
  gdap-maven-dev-local:
    - *Hello_testing  # Alias references the Hello_testing anchor
    - *resuable       # Alias references the resuable anchor
  gdap-maven-prod-local:
    - *Hello_testing  # Alias references the Hello_testing anchor
