repo_mapping:
  Hello_testing: &Hello_testing 854435773
  resuable: &resuable 854566419
  
allowed_jfrog_pushes:
  gdap-maven-dev-local:
    - *Hello_testing
    - *resuable
  gdap-maven-prod-local:
    - *Hello_testing
