name: Reusable Workflow to Download and Upload to JFrog

on:
  workflow_call:
    inputs:
      artifact-prefix:
        description: 'Prefix for the artifact name'
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Generate the artifact name with short SHA and run number
      - name: Generate Artifact Name
        id: generate_artifact_name
        uses: ./github/actions/generate-artifact-name
        with:
          prefix: ${{ inputs.artifact-prefix }}

      # Step 2: Download the artifact using the generated artifact name
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.generate_artifact_name.outputs.artifact_name }}

      # Step 3: Upload to JFrog (or just check that we got the artifact)
      - name: List downloaded files
        run: ls
