name: Reusable Workflow for Downloading Temporary Artifact and Uploading to JFrog

on:
  workflow_call:
    inputs:
      jfrog-artifact-name:
        description: 'The final artifact name to be uploaded to JFrog'
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Download the temporary GitHub artifact
      - name: Download Temporary GitHub Artifact
        uses: actions/download-artifact@v2
        with:
          name: "temp-build-artifact-${{ github.run_number }}"
      -  name: debug
         run: ls -la 

      # Step 3: Upload the unzipped artifact to JFrog using the JFrog artifact name
      - name: Upload to JFrog
        run: |
          echo "Uploading to JFrog with final artifact name: ${{ inputs.jfrog-artifact-name }}"
          jf rt upload "unzipped/*" "your-jfrog-repo/${{ inputs.jfrog-artifact-name }}/"
