name: 'Main Workflow to Call Reusable Workflows and Composite Action'

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Call reusable version workflow
  generate-version:
    uses: pacific-devops/resuable/.github/workflows/reusable-version.yml@main

  # Step 2: Use composite action to zip artifact
  zip-artifact:
    runs-on: ubuntu-latest
    needs: generate-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip artifact with version
        id: zip_step
        uses: ./.github/actions/zip-artifact
        with:
          source: './config'
          destination: './artifacts'
          version: ${{ needs.generate-version.outputs.version }}

  # Step 3: Call reusable deploy workflow
  deploy-artifact:
    needs: zip-artifact
    uses: pacific-devops/resuable/.github/workflows/reusable-deploy.yml@main
    with:
      zip_path: ${{ needs.zip-artifact.outputs.zip_path }}
      destination_repo: 'my-allowed-repo'
