name: JFrog Deployment with Python Validation

on:
  workflow_dispatch:
    inputs:
      destination_repo:
        description: 'JFrog repository to deploy to (user input)'
        required: true

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          pip install requests

      # Step 4: Fetch and validate using Python script
      - name: Fetch and validate allowed repositories
        id: fetch-properties
        run: |
          python ./scripts/check_jfrog_repos.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_DESTINATION_REPO: ${{ github.event.inputs.destination_repo }}  # Pass the user input repo

      # Step 5: Deploy artifacts to JFrog if validation passed
      - name: Upload artifacts to JFrog
        if: success()  # Only run if the validation passed
        run: |
          echo "Deploying to JFrog repository: ${{ steps.fetch-properties.outputs.jfrog_repo }}"
          jf rt upload "artifacts/*" "${{ steps.fetch-properties.outputs.jfrog_repo }}/" --url="${{ secrets.JFROG_URL }}" --apikey="${{ secrets.JFROG_API_KEY }}"
