name: JFrog Deployment with Dynamic Custom Properties

on:
  workflow_call:

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies (if needed)
      run: |
        python -m pip install requests

    - name: Fetch and validate custom properties
      id: fetch-custom-properties
      run: python ./config/repo/check_jfrog_repos.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate API requests
        INPUT_DESTINATION_REPO: 'feature-testing-generic'  # Example input (user-defined repo)
        INPUT_CUSTOM_PROPERTY: 'domain'  # Custom property to fetch from the GitHub repo

    - name: Deploy to JFrog
      if: success()  # Run this only if the previous step succeeded
      run: |
        echo "Deploying to ${{ steps.fetch-custom-properties.outputs.allowed_repo }}"
        # Add your JFrog CLI upload command here using ${{ steps.fetch-custom-properties.outputs.allowed_repo }}
