name: 'Main Workflow'

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Call reusable version workflow
      - name: Generate version
        id: version_step
        uses: ./.github/workflows/reusable-version.yml

      # Step 2: Use composite action to zip artifact
      - name: Zip artifact with version
        id: zip_step
        uses: ./.github/actions/zip-artifact
        with:
          source: './folder-to-zip'
          destination: './artifacts'
          version: ${{ steps.version_step.outputs.version }}

      # Step 3: Call reusable deploy workflow
      - name: Deploy artifact
        uses: ./.github/workflows/reusable-deploy.yml
        with:
          zip_path: ${{ steps.zip_step.outputs.zip_path }}
          destination_repo: 'my-allowed-repo'
