name: JFrog Deployment with User Input Validation

on:
  workflow_dispatch:
    inputs:
      destination_repo:
        description: 'JFrog repository to deploy to (user input)'
        required: true

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Make the script executable
      - name: Make the script executable
        run: chmod +x ./config/repo/check_jfrog_repos.sh

      # Step 3: Call the custom script to fetch and validate allowed JFrog repositories
      - name: Fetch and validate allowed repositories
        id: fetch-properties
        run: |
          ./config/repo/check_jfrog_repos.sh "${{ secrets.GITHUB_TOKEN }}" "${{ github.repository }}"

      # Step 4: Validate the destination repository provided by the user
      - name: Validate user-provided destination repository
        run: |
          # Get the destination repository from the workflow input
          destination_repo="${{ github.event.inputs.destination_repo }}"
          
          # Check if the destination_repo is in the allowed repositories list
          if [[ " ${ALLOWED_REPOS[@]} " =~ " ${destination_repo} " ]]; then
            echo "The repository $destination_repo is allowed."
          else
            echo "The repository $destination_repo is not allowed. Aborting."
            exit 1
          fi

      # Step 5: Upload artifacts to JFrog if validation passed
      - name: Upload artifacts to JFrog
        if: success()  # Only run if the validation passed
        run: |
          echo "Deploying to JFrog repository: ${{ github.event.inputs.destination_repo }}"
          jf rt upload "artifacts/*" "${{ github.event.inputs.destination_repo }}/" --url="${{ secrets.JFROG_URL }}" --apikey="${{ secrets.JFROG_API_KEY }}"
