name: 'Main Workflow to Call Reusable Workflows and Composite Action'

on:
 workflow_call:

jobs:
  # Step 1: Call reusable version workflow
  generate-version:
    uses: pacific-devops/resuable/.github/workflows/reusable-version.yml@main

  # Step 2: Use your composite action to zip artifact
  zip-artifact:
    runs-on: ubuntu-latest
    needs: generate-version
    outputs:
      zip_path: ${{ steps.zip_step.outputs.zip_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Use your composite action to zip the artifact in the current directory
      - name: Zip artifact with version
        id: zip_step
        uses: ./.github/actions/zip-artifact  # This references your composite action
        with:
          source: './config'                # The folder to be zipped
          destination: 'artifact-${{ needs.generate-version.outputs.version }}.zip'  # Zip file will be created in the current directory
          version: ${{ needs.generate-version.outputs.version }}  # Pass the version from the version workflow
      - name: Debug
        run: echo "Zipped file path:${{ steps.zip_step.outputs.zip_path }}"
        

  # Step 3: Call reusable deploy workflow at the top-level 'uses' key
  deploy-artifact:
    needs: [zip-artifact]
    uses: pacific-devops/resuable/.github/workflows/reusable-deploy.yml@main
    with:
      zip_path: ${{ needs.zip-artifact.outputs.zip_path }}  # Access the zip_path output from the previous job
      destination_repo: 'my-allowed-repo'
