name: Main Workflow for Building, Zipping, and Uploading to JFrog

on:
  workflow_dispatch:

jobs:
  # Step 1: Zip files and upload to GitHub with a temporary name
  build-and-upload:
    uses: ./.github/workflows/build_and_zip.yml
    with:
      artifact-file-name: "canvas-final-artifact"
      files-to-zip: "config/*"

  # Step 2: Download the temporary GitHub artifact and upload to JFrog
  download-and-upload:
    needs: build-and-upload
    uses: ./.github/workflows/download_and_upload_to_jfrog.yml
    with:
      jfrog-artifact-name: ${{ steps.build-and-upload.outputs.jfrog_artifact_name }}
