name: JFrog Deployment with Custom Properties

on:
  workflow_dispatch:
    inputs:
      destination_repo:
        description: 'Enter the destination repository (e.g., feature-testing-generic)'
        required: true
env:
 destination_repo: 'feature-testing-generic'

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies (if needed)
      run: |
        python -m pip install requests

    - name: Fetch custom properties and write to output
      id: fetch-custom-properties
      run: python ./config/repo/check_jfrog.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate API requests
        INPUT_CUSTOM_PROPERTY: jfrog_repo  # Dynamic input for custom property

    - name: Check if the destination repo is in the allowed list
      run: |
        allowed_repos="${{ steps.fetch-custom-properties.outputs.jfrog_repo }}"
        echo "Allowed Repositories: $allowed_repos"
         # Check if the destination repo is in the list of allowed repos
         if echo "$allowed_repos" | grep -q "${{env.destination_repo}}"; then
         echo "The repository ${{env.destination_repo}} is allowed."
         else
         echo "The repository ${{env.destination_repo}} is not allowed. Aborting."
         exit 1
         fi

    - name: Deploy to JFrog
      if: success()  # Run this only if the previous step succeeded
      run: |
        echo "Deploying to JFrog..."
        # Add your JFrog CLI upload command here
