name: Reusable Deployment Workflow

on:
  workflow_call:
    inputs:
      technology:
        description: "Enter the technology (e.g., maven, generic, dev)"
        required: true
        type: string
      team:
        description: "Enter the team name"
        required: true
        type: string

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Checkout reusable workflow repository (to get release config)
      uses: actions/checkout@v4
      with:
          repository: pacific-devops/resuable  
          path: resuable
          fetch-depth: 1
    - name: Copy release config file from reusable workflow
      if: env.COPY_REQUIRED == 'true'
      run : |
            mv resuable/config/repo-mapping.json  ./
            ls -la 

    - name: Get GitHub repository name dynamically from calling repo
      id: get_repo_name
      run: |
        repo_full_name="${{ github.repository }}"  # This gives owner/repo
        repo=$(echo $repo_full_name | cut -d'/' -f2)  # Extract just the repo part
        echo "Repository name is: $repo"
        echo "REPO_NAME=$repo" >> $GITHUB_ENV
