name: Reusable Deployment Workflow

on:
  workflow_call:
    inputs:
      technology:
        description: "Enter the technology (e.g., maven, generic, dev)"
        required: true
        type: string
      team:
        description: "Enter the team name"
        required: true
        type: string
      domain:
        description: "Enter the domain name"
        required: true
        type: string
        
permissions:
  id-token: write
  contents: write
  
jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Checkout reusable workflow repository (to get config)
      uses: actions/checkout@v4
      with:
          repository: pacific-devops/resuable  
          path: master
          fetch-depth: 1
    - name: Copy config file from reusable workflow
      run : |
            ls -la
            mv master/config/repo/repo-mapping.json  ./
            ls -la 

    - name: Get GitHub repository name dynamically from calling repo
      id: get_repo_name
      run: |
        repo_full_name="${{ github.repository }}"  # This gives owner/repo
        repo=$(echo $repo_full_name | cut -d'/' -f2)  # Extract just the repo part
        echo "Repository name is: $repo"
        echo "REPO_NAME=$repo" >> $GITHUB_ENV
        
    - name: Read repository mapping file and determine JFrog repo based on domain and technology
      id: read_mapping
      run: |
        repo="${{ env.REPO_NAME }}"
        technology="${{ inputs.technology }}"
        domain="${{ inputs.domain }}"  # Get the domain input

        # Read the mapping from the file and extract the relevant domain and JFrog repository
        jfrog_repo=$(jq -r --arg repo "$repo" --arg domain "$domain" --arg tech "$technology" '.repositories[$repo].domains[$domain][$tech]' repo-mapping.json)

        if [[ "$jfrog_repo" == "null" ]]; then
          echo "Repository $repo or domain $domain with technology $technology is not allowed to deploy. No mapping found."
          exit 1
        fi

        echo "JFrog repository for $repo with domain $domain and technology $technology is $jfrog_repo"
        echo "JFROG_REPO=$jfrog_repo" >> $GITHUB_ENV
