name: 'Generate Version Workflow'

on:
  workflow_call:
    outputs:
      version:
        description: 'Generated version number'
        value: ${{ jobs.generate_version.outputs.version }}  # Correct value reference

jobs:
  generate_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_output.outputs.version }}  # This references the output of the step
    steps:
      - name: Generate version
        id: version_output
        run: |
          VERSION="1.0.$(date +%s)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
