name: Reusable Workflow - Generate Artifact Name

on:
  workflow_call:
    outputs:
      artifact_name:
        description: 'The generated artifact name'
        value: ${{ jobs.generate-artifact.outputs.artifact_name }}  # Link the job output to the workflow_call output

jobs:
  generate-artifact:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.generate.outputs.artifact_name }}  # Define output

    steps:
      - name: Generate Artifact Name
        id: generate
        run: |
          ARTIFACT_NAME="artifact-$(date +%s)"
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
          echo "Generated artifact name: $ARTIFACT_NAME"

      - name: Debug Artifact Name
        run: |
          echo 'Artifact name is: ${{ steps.generate.outputs.artifact_name }}'
