name: Reusable Workflow for Zipping and Uploading GitHub Artifact

on:
  workflow_call:
    inputs:
      artifact-file-name:
        description: 'The final JFrog artifact file name'
        required: true
        type: string
      files-to-zip:
        description: 'The list of files to zip and upload'
        required: true
        type: string

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Generate both artifact names (temporary for GitHub, standard for JFrog)
      - name: Generate Artifact Names
        uses: ./.github/actions/zip-artifact
        with:
          artifact-file-name: ${{ inputs.artifact-file-name }}

      # Step 2: Zip the provided files using the temporary GitHub artifact name
      - name: Zip the files
        run: |
          ZIP_NAME="${{ steps.generate-artifact-names.outputs.temp_artifact_name }}.zip"
          echo "Zipping files into: $ZIP_NAME"
          zip -r $ZIP_NAME ${{ inputs.files-to-zip }}

      # Step 3: Upload the zip file as a GitHub artifact using the temporary artifact name
      - name: Upload Temporary GitHub Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.generate-artifact-names.outputs.temp_artifact_name }}
          path: ./*.zip

      # Optional: Log the JFrog artifact name (for clarity)
      - name: Log JFrog Artifact Name
        run: echo "JFrog Artifact Name:${{ steps.generate-artifact-names.outputs.jfrog_artifact_name }}"
