name: Reusable Workflow for Zipping and Uploading Artifact

on:
  workflow_call:
    inputs:
      artifact-prefix:
        description: 'Prefix for the artifact name'
        required: true
        type: string

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Generate the artifact name with short SHA and run number
      - name: Generate Artifact Name
        id: generate_artifact_name
        uses: ./.github/actions/generate-artifact-name
        with:
          prefix: ${{ inputs.artifact-prefix }}

      # Step 2: Create a sample file or folder to zip
      - name: Create a sample file
        run: |
          echo "This is a test file for artifact upload" > sample.txt

      # Step 3: Zip the file and upload as artifact
      - name: Zip the file
        run: |
          ZIP_NAME="${{ steps.generate_artifact_name.outputs.artifact_name }}.zip"
          zip $ZIP_NAME sample.txt
          echo "Zipped file: $ZIP_NAME"

      # Step 4: Upload the zip file using the dynamically generated name
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.generate_artifact_name.outputs.artifact_name }}
          path: ./*.zip
